name: Run JavaScript Code on Commit to Main
on:
  push:
    branches:
      - main

jobs:
  run-js-code:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' # Specify the Node.js version you need

      - name: Install dependencies
        run: npm install
    
      - name: AWS Security Group Add IP
        uses: sohelamin/aws-security-group-add-ip-action@v1.0.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'
          aws-security-group-id: ${{ secrets.AWS_SECURITY_GROUP_ID }}
          port: '27017'
          to-port: ''
          protocol: 'tcp'
          description: 'GitHub Actions'

      - name: Run script
        run: node index.js # Assuming the script to run is index.js
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          DB_NAME: ${{ secrets.DB_NAME }}
      
      - name: Commit and push changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add blog-status.json
          git commit -m "Update blog status"
          git push